baseurl = "https://ricardoanderegg.com/"
languageCode = "en-US"
title = "rand[om]"
locale = "en"


pygmentsstyle = "vs"
# pygmentsUseClasses = true
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  # title = "rand[om]"
  subtitle = "med âˆ© ml"
  subsubtitle = ""
  avatar = "/img/bike_m.png"
  favicon = true
  dateFormat = "January 2, 2006"
  featherIconsCDN = false
  mode = "auto"
  rss = true

  # favicon = "img/favicon.ico"
  # readingTime = true
  # useHLJS = true
  # social = true
  # hideAuthor = true

[Author]
  name = "Ricardo Ander-Egg"
  website = "ricardoanderegg.com"
  # email = "ricardo.anderegg@gmail.com"
  github = "polyrand"
  gitlab = "polyrand"
  twitter = "ricardoanderegg"
  linkedin = "ricardoanderegg"
  telegram = "rick_dolphin"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Code"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "Think"
    url = "/thoughts"
    weight = 3
    
[[menu.main]]
    name = "Recipes"
    url = "/recipes"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 5

[taxonomies]
  # category = "categories"
  tag = "tags"


# [[params.social]]
#   name = "Github"
#   icon = "github"
#   url = "https://github.com/polyrand"
# 
# [[params.social]]
#   name = "LinkedIn"
#   icon = "linkedin"
#   url = "https://www.linkedin.com/in/ricardoanderegg/"
# 
# [[params.social]]
#   name = "Twitter"
#   icon = "twitter"
#   url = "https://twitter.com/ricardoanderegg"

# [[params.social]]
#   name = "Telegram"
#   icon = "send"
#   url = "https://t.me/polyrand"

# [[params.social]]
#   name = "Mail"
#   icon = "mail"
#   url = "mailto:ricardo.anderegg@gmail.com"

# [[params.social]]
#   name = "RSS"
#   icon = "rss"
#   url = "/index.xml"
